namespace ExamShield.Domain.Enums;

public enum AuditAction
{
    UserCreated,
    DeviceRegistered,
    CaptureRegistered,
    ImageUploaded,
    HashVerified,
    TamperingDetected,
    ManualReviewStarted,
    ManualReviewCompleted,
    OCRStarted,
    OCRCompleted,
    ScoreGenerated,
    ResultPublished,
    ResultsPublished,
    ReviewRequestSubmitted,
    AnswerKeySet,
    StudentEnrolled,
    StudentUnenrolled,
    UserRoleChanged,
    UserDeactivated,
    UserReactivated,
    PasswordChanged,
    DeviceEnabled,
    DeviceDisabled,
    ReviewApproved,
    ReviewRejected,
    SettingsUpdated,
    MfaDisabled,
    PasswordReset,
    DeviceApproved,
    DeviceBlacklisted,
    ReviewEscalated,
    UserLoggedIn,
    UserLoggedOut
}
